### ISSUE TITLE
OpenAPIドキュメントの更新

### ISSUE THREAD

**Issue by YutoFuruya** [Personal-Data-Linkage-Module/pxr-catalog-service#7]
```[tasklist]
### Tasks
- [ ] PUT /name
- [ ] GET /name
- [ ] GET /public
- [ ] GET /{code}
- [ ] GET /{code}
- [ ] GET /{code}/{ver}
- [ ] POST /
- [ ] GET /
- [ ] GET /inner/{code}/{name}
- [ ] GET /{code}/{ver}/{name}
- [ ] GET /ns
- [ ] POST /ns/ext
- [ ] PUT ns/ext/{nsId}
- [ ] DELETE /ns/ext/{nsId}
- [ ] POST /ext
- [ ] PUT /ext/{code}
- [ ] DELETE /ext/{code}
- [ ] GET /updateSet/search/info/{id}
- [ ] GET /updateSet/search/request
- [ ] GET /updateSet/search/approval
- [ ] POST /updateSet/register
- [ ] PUT /updateSet/register/{id}
- [ ] DELETE /updateSet/register/{id}
- [ ] POST /updateSet/request
- [ ] POST updateSet/approval/{id}
```
